apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx1
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [nginx_1, nginx_2]}
  template:
    metadata:
      name: nginx
      labels:
        app: nginx_2
    spec:
      containers:
        - image: nginx:latest
          name: nginx

